pub const DEPOSIT_RESERVE_LIQUIDITY: u8 = 4;
pub const INIT_OBLIGATION: u8 = 6;
pub const DEPOSIT_OBLIGATION_COLLATERAL: u8 = 8;
pub const BORROW_OBLIGATION_LIQUIDITY: u8 = 10;
pub const REPAY_OBLIGATION_LIQUIDITY: u8 = 11;
